<!DOCTYPE html>
<html lang="en">
<html>
    <head>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		
        <title>Maquillajes Gio</title>
		<link rel="stylesheet" href="css/style.css">
    </head>
    <body>
		<section class="navbar">
			<h1>
				<ul class="navega">
					<li><a href="home.html">Inicio</a></li>
					<li><a href="https://www.instagram.com/noneeherraiz/?hl=es" target="_blank">Instagram</a></li>
					<li><a href="contacto.html">Contacto</a></li>
				</ul>
			</h1>
		</section>
		<section class="logo-img">
			<a href="home.html"><img src="img/.jpg"></a>
		</section>
		<section class="cab">
			<h1>
				Maquilladora profesional Madrid
			</h1>
			<h3>
				Texto texto texto texto texto texto texto texto texto texto texto texto texto texto texto texto 
				texto texto texto texto texto texto texto texto texto texto texto texto texto texto texto texto 
				texto texto texto texto texto texto texto texto texto texto texto texto texto texto texto texto 
				texto texto texto texto texto texto texto texto texto texto texto texto texto texto texto texto
			</h3>
			
		</section>
		<section>
			<div class="slide">
				<div class="slide-inner">
					<input class="slide-open" type="radio" id="slide-1" name="slide" aria-hidden="true" hidden="" checked="checked">
					<div class="slide-item">
						<img src="img/ofer1.jpg">
					</div>
					<input class="slide-open" type="radio" id="slide-2" name="slide" aria-hidden="true" hidden="">
					<div class="slide-item">
						<img src="img/ofer2.jpg">
					</div>
					<input class="slide-open" type="radio" id="slide-3" name="slide" aria-hidden="true" hidden="">
					<div class="slide-item">
						<img src="img/ofer3.jpg">
					</div>
					<label for="slide-3" class="slide-control prev control-1">‹</label>
					<label for="slide-2" class="slide-control next control-1">›</label>
					<label for="slide-1" class="slide-control prev control-2">‹</label>
					<label for="slide-3" class="slide-control next control-2">›</label>
					<label for="slide-2" class="slide-control prev control-3">‹</label>
					<label for="slide-1" class="slide-control next control-3">›</label>
					<ol class="slide-indicador">
						<li>
							<label for="slide-1" class="slide-circulo">•</label>
						</li>
						<li>
							<label for="slide-2" class="slide-circulo">•</label>
						</li>
						<li>
							<label for="slide-3" class="slide-circulo">•</label>
						</li>
					</ol>
				</div>
			</div>
		</section>
    </body>
</html>
